spring.application.name=courses-reactive-example
server.port=9595
# Show the sql queries in the logger.
spring.jpa.show-sql=true
spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.name=sa
spring.r2dbc.password=password
# (Optional) Format the logged queries for a more readable way.
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.data.r2dbc=DEBUG
spring.h2.console.enabled=true

