spring.application.name=courses-reactive-example
server.port=9595
# Show the sql queries in the logger.
spring.jpa.show-sql=true
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres?schema=course
spring.r2dbc.username=user_postgresql
spring.r2dbc.password=user_postgresql
# (Optional) Format the logged queries for a more readable way.
spring.jpa.properties.hibernate.format_sql=none
logging.level.org.springframework.data.r2dbc=DEBUG
#liquibase configuration
spring.liquibase.url=jdbc:postgresql://localhost:5432/postgres
spring.liquibase.user=user_postgresql
spring.liquibase.password=user_postgresql
spring.liquibase.change-log=db/changelog/changelog.xml
spring.liquibase.default-schema=course
spring.liquibase.drop-first=true
spring.liquibase.enabled=true

